# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-20 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_last_login_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.CharField(default='1994-02-17', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='graduate_time',
            field=models.CharField(default='2016-06-20', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(default='2017-06-01', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='job_join_time',
            field=models.CharField(default='2017-06-01', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='job_number',
            field=models.CharField(default='0001', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='沈峰', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='18361296750', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(default='江苏师范大学', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default='男', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='team_belong',
            field=models.CharField(default='C640', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='xue_li',
            field=models.CharField(default='本科', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='zhengzhi_mianmao',
            field=models.CharField(default='群众', max_length=10),
        ),
    ]
