# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-20 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180920_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_time',
            field=models.CharField(default='2017-06-01', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(default='工程师', max_length=30),
        ),
    ]
